### ISSUE TITLE
403 response

### ISSUE THREAD

**Issue by ledwindra** [ledwindra/indonesia-stock-exchange#1]
why the heck this happens?

**Comment by ledwindra** [comment]
Even after changing headers

```python
headers = {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.5',
    'Connection': 'keep-alive',
    'DNT': '1',
    'Host': 'idx.co.id',
    'TE': 'Trailers',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0'
}

response = session.get('https://idx.co.id/umbraco/Surface/TradingSummary/GetStockSummary?date=2021-02-25', headers=headers)
response
<Response [403]>
```

**Comment by syaifurrizal** [comment]
Halo, biasanya saya ambil data laporan keuangan via data JSON dengan pagesize 1000 biar langsung dapat semua. Tapi beberapa hari terakhir jumlah pagesize dibatasi. Terakhir coba bisanya 50 lalu mengganti indexFrom dari 1, 2, dan seterusnya.

Mungkin apa yang Anda alami juga sama. Ada pembatasan feed data dari IDX.

https://www.idx.co.id/umbraco/Surface/ListedCompany/GetFinancialReport?indexFrom=1&pageSize=10000&year=2020&reportType=rdf&periode=audit&kodeEmiten=

**Comment by ledwindra** [comment]
Hi @syaifurrizal 

Terima kasih feedbacknya. Menarik. Saya akan coba telusuri lebih lanjut, kalau tetap tidak berhasil mungkin repo ini cukup di-archive saja haha

**Comment by syaifurrizal** [comment]
Jangan dong bang. Ini nyari portfolio manager macam sharesight.com atau simplywall.st yang affordable gak nemu. 😂

Ada situs stockbit.com tapi cuman data pasar & fundamental. Itupun masih mahal. 😂😂
